-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2025-10-02 09:49:35 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE customer (
    customer_id   NUMBER NOT NULL,
    name          VARCHAR2(20) NOT NULL
);

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE customers_orders (
    customer_customer_id   NUMBER NOT NULL,
    orders_order_id        NUMBER NOT NULL
);

ALTER TABLE customers_orders ADD CONSTRAINT customers_orders_pk PRIMARY KEY ( customer_customer_id,
                                                                              orders_order_id );

CREATE TABLE orders (
    order_id    NUMBER NOT NULL,
    food_item   VARCHAR2(30) NOT NULL
);

ALTER TABLE orders ADD CONSTRAINT orders_pk PRIMARY KEY ( order_id );

ALTER TABLE customers_orders
    ADD CONSTRAINT customers_orders_customer_fk FOREIGN KEY ( customer_customer_id )
        REFERENCES customer ( customer_id );

ALTER TABLE customers_orders
    ADD CONSTRAINT customers_orders_orders_fk FOREIGN KEY ( orders_order_id )
        REFERENCES orders ( order_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
